# 데이터 전처리
ML 알고리즘은 데이터에 기반을 하고 있기 떄문에 어떤 데이터를 입력하느냐에 따라 결과도 크게 달라질 수 있따. 그러므로 우리는 데이터를 넣어주기 전에 **데이터 전처리**를 해야 한다.

## 1. 데이터 전처리 시 기본사항
### 1.1. 결손값(Missing Value)는 허용되지 않는다.
`Nan`, `NULL`로 나타나는 결손값은 머신러닝 알고리즘이 인식하지 못하므로 **고정된 다른 값**을 변환해주어야 한다.
* `NULL`값이 적은 경우 : 피처의 평균값 등으로 간단히 대체
* `NULL`값이 많은 경우 : 해당 피처를 삭제(drop)
* `NULL`값이 일정 이상인 경우 : 중요도가 높은 피처일 경우 업무 로직 등을 상세히 검토해 더 정밀한 대체값을 선정

### 1.2. 문자열 값은 입력 값으로 허용되지 않는다.
사이킷런 머신러닝 알고리즘은 문자열 값을 읽을 수 없으므로 모든 문자열 값을 인코딩하여 숫자형으로 변환해야 한다.
* `카테고리형 피처` : 코드 값으로 표기하는 것 
* `텍스트형 피처` : 피처 벡터화 등을 통해 벡터화 or 해당 피처 삭제(drop)
    * 주민번호, 아이디는 단순히 행을 식별하는 용도이기 때문에 예측을 하는데 중요한 척도가 되지 않으므로 삭제하는 게 좋다.

## 2. 데이터 인코딩
### 2.1. 레이블 인코딩
레이블 인코딩은 **카테고리 피처를 코드형 숫자 값으로 변환**하는 것이다. 예를 들어 `TV`, `냉장고`, `에어컨`과 같이 세 가지의 카테고리가 있다면 각각 `1`, `2`, `3`으로 숫자형 값으로 매겨주는 것이다. 이 때 `01`, `02`도 문자열이므로 `1`, `2`로 바꿔주어야 한다.

In [2]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']

# LabelEncoder 객체 생성
encoder = LabelEncoder()
# fit()과 transform()으로 레이블 인코딩
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 : ', labels)

인코딩 변환값 :  [0 1 4 5 3 2 2]


데이터가 많아서 어떤 문자열 값이 어떤 숫자 값으로 인코딩되었는지 알기 어려운 경우 `classes_` 속성값을 확인할 수 있다.

In [3]:
print('인코딩 클래스 : ', encoder.classes_)

인코딩 클래스 :  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


`inverse_transform()`으로 숫자 값을 문자열 값으로 다시 디코딩할 수 있다.

In [4]:
print('디코딩 원본 값 : ', encoder.inverse_transform([4, 5, 2, 0, 1, 3, 3]))

디코딩 원본 값 :  ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '선풍기' '선풍기']


레이블 인코딩은 문자열 값을 일괄적인 숫자 값으로 변환이 되는데 이는 몇몇 ML 알고리즘에 적용할 경우 **예측 성능을 저하**시킬 수 있다. 왜냐하면 몇몇 ML 알고리즘의 경우 숫자 값이 큰지 작은지에 대한 특성이 작용하여 **큰 값일수록 가충지를 더 부여하여 더 중요하게 인식될 수 있기 때문**이다.    

그러므로 선형 회귀와 같은 ML 알고리즘에 레이블 인코딩 대신 **웟-핫 인코딩**을 사용해야 한다. 트리 계열의 알고리즘은 이러한 특징을 반영하지 않으므로 레이블 인코딩을 써도 된다.

### 2.2. 원-핫 인코딩
웟-핫 인코딩은 행 행태로 되어 있는 피처의 고유 값들을 열 형태로 차원을 변환한 뒤, **고유 값에 해당하는 열에만 1을 표시하고 나머지 열에는 0을 표시**하는 것이다. 여러 개의 속성 중 단 한 개의 속성만 1로 표시하는 특징때문에 원-핫 인코딩이라 부른다.

#### 주의할 점
* `OneHotEncoder`로 변환하기 전에 모든 문자열 값이 숫자 값으로 변환되어야 한다.
* 입력 값으로 2차원 데이터가 필요하다.

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder로 숫자 값으로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('숫자 값으로 변환 후 : \n', labels)

# 2차원 데이터로 변환
labels = labels.reshape(-1, 1)
print('2차원 데이터로 변환후 : \n', labels)

# 원-핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원 핫 인코딩 데이터 : \n', oh_labels.toarray())
print('원 핫 인코딩 데이터 차원 : \n', oh_labels.shape)

숫자 값으로 변환 후 : 
 [0 1 4 5 3 3 2 2]
2차원 데이터로 변환후 : 
 [[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]
원 핫 인코딩 데이터 : 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원 핫 인코딩 데이터 차원 : 
 (8, 6)


C:\Users\round\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


판다스의 `get_dummies()`를 이용하면 숫자형으로 변환할 필요 없이 인코딩을 할 수 있다.

In [6]:
import pandas as pd

df = pd.DataFrame({'items' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

## 3. 피처 스케일링과 정규화
피처 스케일링이란 **서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 것**을 말한다.
* `표준화(Standardization)` : 데이터의 피처 각각이 평균이 0이고 분산이 1인 가우시안 정규 분포를 가진 값으로 변환
$$x_{i, new} = \frac{x_i - mean(x)}{stdev(x)}$$
* `정규화(Nomalization)` : 서로 다른 피처의 크기를 통일하기 위해 크기를 변환 (0 ~ 1로 변환)
$$x_{i, new} = \frac{x_i - min(x)}{max(x) - min(x)}$$
* `벡터 정규화(Vector Nomalization)` : 개별 벡터의 크기를 맞추기 위해 변환
$$x_{i, new} = \frac{x_i}{\sqrt{x_i^{2}+y_i^{2}+z_i^{2}}}$$

### 3.1. `StandardScaler` (표준화, Standardization)
`StandardScaler`는 개별 피처를 **평균이 0**이고, **분산이 1**인 값으로 변환(가우시안 정규 분포)해주는 클래스이다. 특히 `SVM`, `선형회귀`, `로지스틱 회귀`의 경우 데이터가 가우시안 분포를 가지고 있다 가정되고 구현되어 있기 때문에 쓰기 전에 데이터를 정규화시켜줘야 한다.

In [7]:
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터 세트를 로딩
iris = load_iris()
iris_data = iris.data

# DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature들의 평균 값 : \n', iris_df.mean())
print('\nfeature들의 분산 값 : \n', iris_df.var())

feature들의 평균 값 : 
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값 : 
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [10]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# StandardScaler로 데이터 세트 변환
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()시 반환되는 데이터 세트가 ndarray이므로 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 평균 값 : \n', iris_df_scaled.mean())
print('\nfeature들의 분산 값 : \n', iris_df_scaled.var())

feature들의 평균 값 : 
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값 : 
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### 3.2. `MinMaxScaler` (정규화, Normalization)
`MinMaxScaler`는 데이터 값을 **0 과 1 사이의 범위 값**으로 변환해주는 클래스이다. 음수가 있으면 **-1과 1 사이의 범위 값**으로 변환한다.

In [11]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# MinMaxScaler로 데이터 세트 변환
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 반환된 데이터 세트의 자료형이 ndarray이므로 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최소값 : \n', iris_df_scaled.min())
print('\nfeature들의 최대값 : \n', iris_df_scaled.max())

feature들의 최소값 : 
 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대값 : 
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
