# Numpy
파이썬에서 선형대수 기반의 프로그램을 쉽게 만들수 있도록 지원하는 대표적인 패키지    
* 배열 기반의 연산과 다양한 데이터 핸들링 기능 제공
* 많은 알고리즘 입출력 데이터로 넘파일 배열 타입을 이용

## 1. 넘파이 ndarray 개요
넘파이의 기반 데이터 타입은 ndarray이다. ndarray를 이용해 다차원 배열을 쉽게 생성하고 연산을 할 수 있다.
* `np.array()` : 매개변수로 리스트를 받아서 ndarray형태로 반환
* `shape` : ndarray의 크기를 튜플 형태로 반환
* `ndim` : ndarray의 차원을 반환

In [1]:
import numpy as np

array1 = np.array([1, 2, 3])                   # 1차원 배열
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape)

array2 = np.array([[1, 2, 3],                  # 2차원 배열
                   [4, 5, 6]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)

array3 = np.array([[1, 2, 3]])                 # 2차원 배열
print('array3 type : ', type(array3))
print('array3  array 형태 : ', array3.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
array3 type :  <class 'numpy.ndarray'>
array3  array 형태 :  (1, 3)


In [2]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


## 2. ndarray의 데이터 타입
ndarray내의 데이터 값은 숫자 값, 문자열 값, 불 값 등 모두 가능하지만 모든 요소들의 데이터 타입이 같아야 한다.
* `dtype` : ndarray 내의 데이터 타입 반환

In [3]:
list1 = [1, 2, 3]
print(type(list1))            # list1의 데이터 타입 반환
array1 = np.array(list1)
print(type(array1))           # array1의 데이터 타입 반환
print(array1, array1.dtype)   # array1의 요소들의 데이터 타입 반환

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


만약 다른 데이터 타입이 섞여 있는 경우 데이데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

In [4]:
# int와 string 데이터 타입이 섞여있는 경우
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

# int와 float 데이터 타입이 섞여있는 경우
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


크기가 큰 데이터의 ndarray를 만들 때 메모리 절약을 위해 데이터 타입을 변경하기도 한다.
* `astype()` : 매개변수로 원하는 데이터 타입을 문자열로 넣으면 해당 데이터 타입으로 일괄 형변환을 한다.

In [5]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')    # int -> float
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')     # float -> int
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')    # float -> int
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## 3. ndarray를 편리하게 생성하기 - arange, zeros, ones
테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화하고 싶을 경우
* `arange()` : 0부터 매개변수-1까지의 값을 순차적으로 데이터값으로 변환 (int32)
* `zeros()` : 매개변수로 튜플 타입의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
* `ones()` : `zeros()`와 비슷하게 1로 채운 ndarray를 반환
    * dtype을 명시하지 않을 경우 float64 타입의 값으로 ndarray를 채움

In [6]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

sequence_array2 = np.arange(5, 15)
print(sequence_array2)
print(sequence_array2.dtype, sequence_array2.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[ 5  6  7  8  9 10 11 12 13 14]
int32 (10,)


In [7]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## 4. ndarray의 차원과 크기를 변경하는 reshape()
`reshape()` 메서드는 변환을 원하는 크기를 매개변수에 넣어주면 ndarray를 특정 차원 및 크기로 반환한다.

In [8]:
arr1 = np.arange(10)
print('arr1 : \n', arr1)

arr2 = arr1.reshape(2, 5)
print('arr2 : \n', arr2)

arr3 = arr1.reshape(5, 2)
print('arr3 : \n', arr3)

arr1 : 
 [0 1 2 3 4 5 6 7 8 9]
arr2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


단, `reshape()`는 모든 요소들이 다 들어갈 수 있는 크기로 변경 가능하지만, 조금 더 큰 사이즈나 조금 더 작은 사이즈일 경우 `ValueError` 메시지를 출력한다.

In [9]:
arr1.reshape(4, 3)     # ValueError

ValueError: cannot reshape array of size 10 into shape (4,3)

`reshape()`에 인자로 -1을 적용할 경우, 나머지 인자는 행 또는 열의 고정값이 되고 남은 열 또는 행은 그 값에 맞추어 값이 설정된다.

아래 예제의 경우 `arr1`은 `1*10` 크기인데, `arr2`에서 열인 `5`가 고정이 되므로 행은 거기에 맞춰 `2`가 되므로 `2*5` 크기가 된다 `arr3`의 경우도 행인 `5`가 고정이 되므로 열은 거기에 맞춰 `2`가 되므로 `5*2` 크기가 된다.

In [10]:
arr1 = np.arange(10)
print(arr1)

arr2 = arr1.reshape(-1, 5)
print('arr2 shape : ', arr2.shape)

arr3 = arr1.reshape(5, -1)
print('arr3 shape : ', arr3.shape)

[0 1 2 3 4 5 6 7 8 9]
arr2 shape :  (2, 5)
arr3 shape :  (5, 2)


단, 이 경우도 크기가 딱 맞아 떨어지지 않는 경우 `ValueError`를 발생시킨다.

In [11]:
arr1 = np.arange(10)
arr4 = arr1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

`reshape(-1, 1)`는 ndarray의 크기를 통일하고 싶을 때 사용된다.
* 항상 2차원이다.
* 1개의 column을 가진 ndarray이다.

(`tolist()`는 ndarray를 list로 변환한다.)

In [12]:
arr1 = np.arange(8)
arr3d = arr1.reshape((2,2,2))
print('arr3d : \n', arr3d.tolist())

# 3차원 ndarray -> 2차원 ndarray
arr5 = arr3d.reshape(-1, 1)
print('arr5 : \n', arr5.tolist())
print('arr5 shape : ', arr5.shape)

# 1차원 ndarray -> 2차원 ndarray
arr6 = arr1.reshape(-1, 1)
print('arr6 : \n', arr6.tolist())
print('arr6 shape : ', arr6.shape)

arr3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
arr5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr5 shape :  (8, 1)
arr6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr6 shape :  (8, 1)


## 5. Numpy의 ndarray의 데이터 세트 선택하기 - 인덱싱
인덱싱이란 ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택하는 것을 말한다.

### 5.1. 단일 값 추출

한 개의 데이터만 추출하는 방법이다.
* 해당 위치의 인덱스 값을 입력하면 된다. -> 1차원 : [] / 2차원 : [,]
* `-`를 이용하면 맨 뒤에서부터 데이터에 접근할 수 있다. -> 맨 앞의 시작 : 0, 맨 뒤의 시작 : -1
* row를 `axis 0`, column을 `axis 1`이라 한다.

In [13]:
# 1부터 9까지의 1차원 ndarray 생성
arr1 = np.arange(start=1, stop=10)
print('arr1 : ', arr1)

value = arr1[2]
print('value : ', value)
print(type(value))

arr1 :  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>


In [14]:
print('맨 뒤의 값 : ', arr1[-1], ' 맨 뒤에서 두 번째 값 : ', arr1[-2])

맨 뒤의 값 :  9  맨 뒤에서 두 번째 값 :  8


In [15]:
# 값 수정도 가능
arr1[0] = 9
arr1[8] = 0
print('arr1 : ', arr1)

arr1 :  [9 2 3 4 5 6 7 8 0]


In [16]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3, 3)
print(arr2d)

print('(row=0, col=0) index 가리키는 값 : ', arr2d[0, 0])
print('(row=0, col=1) index 가리키는 값 : ', arr2d[0, 1])
print('(row=1, col=0) index 가리키는 값 : ', arr2d[1, 0])
print('(row=1, col=1) index 가리키는 값 : ', arr2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값 :  1
(row=0, col=1) index 가리키는 값 :  2
(row=1, col=0) index 가리키는 값 :  4
(row=1, col=1) index 가리키는 값 :  9


### 5.2. 슬라이싱


연속한 데이터를 추출하는 방법이다.
* `:`기호를 이용한다.
* 시작인덱스에서 종료인덱스-1까지의 데이터를 반환한다.
* 반환된 데이터는 ndarray타입이다.

In [17]:
arr1 = np.arange(start=1, stop=10)
arr3 = arr1[0:3]
print(arr3)
print(type(arr3))

[1 2 3]
<class 'numpy.ndarray'>


`:`의 시작, 종료 인덱스는 생략이 가능하다.
* 시작인덱스 없는 경우 : 0부터 시작
* 종료인덱스 없는 경우 : 맨 마지막 인덱스에서 종료
* 둘 다 없는 경우 : 배열 전체

In [18]:
arr1 = np.arange(start=1, stop=10)
arr4 = arr1[:3]
print(arr4)

arr5 = arr1[3:]
print(arr5)

arr6 = arr1[:]
print(arr6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [19]:
# 2차원 ndarray 슬라이싱
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3, 3)
print('arr2d : \n', arr2d)

print('arr2d[0:2, 0:2] \n', arr2d[0:2, 0:2])
print('arr2d[1:3, 0:3] \n', arr2d[1:3, 0:3])
print('arr2d[1:3, :] \n', arr2d[1:3, :])
print('arr2d[:, :] \n', arr2d[:, :])
print('arr2d[:2, 1:] \n', arr2d[:, :])
print('arr2d[:2, 1:] \n', arr2d[:2, 1:])
print('arr2d[:2, 0:] \n', arr2d[:2, 0:])

arr2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
arr2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
arr2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
arr2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[:2, 1:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[:2, 1:] 
 [[2 3]
 [5 6]]
arr2d[:2, 0:] 
 [[1 2 3]
 [4 5 6]]


In [20]:
# 2차원 ndarray에서 한 인덱스만 쓰면 1차원 ndarray를 반환
print(arr2d[0])
print(arr2d[1])
print('arr2d[0] shape : ', arr2d[0].shape, 'arr2d[1] shape : ', arr2d[1].shape)

[1 2 3]
[4 5 6]
arr2d[0] shape :  (3,) arr2d[1] shape :  (3,)


### 5.3. 팬시 인덱싱
리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 방법이다.

In [21]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3, 3)

arr3 = arr2d[[0, 1], 2]
print('arr2d[[0, 1], 2] => ', arr3.tolist())

arr4 = arr2d[[0, 1], 0:2]
print('arr2d[[0, 1], 0:2] => ', arr4.tolist())

arr5 = arr2d[[0, 1]]
print('arr2d[[0, 1]] => ', arr5.tolist())

arr2d[[0, 1], 2] =>  [3, 6]
arr2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]
arr2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]


### 5.4. 불린 인덱싱
조건 필터링과 검색을 동시에 할 수 있는 방법이다.
* ndarray의 인덱스를 지정하는 `[]`내에 조건문을 넣는다.
* 해당 조건문을 충족하는 요소들을 ndarray로 반환한다.

In [22]:
arr1d = np.arange(start=1, stop=10)

# [] 안에 arr1d > 5 Boolean Indexing을 적용
arr3 = arr1d[arr1d > 5]
print('arr1d > 5 불린 인덱싱 결과 값 : ', arr3)

arr1d > 5 불린 인덱싱 결과 값 :  [6 7 8 9]


조건으로 반환된 ndarray객체를 인덱싱을 지정하는 `[]`내에 입력하면 False값은 무시하고 True값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환한다.

In [23]:
arr1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [24]:
bool_indexes = np.array([False, False, False, False, False, True, True, True, True])
arr3 = arr1d[bool_indexes]
print('불린 인덱스로 필터링 결과 : ', arr3)

불린 인덱스로 필터링 결과 :  [6 7 8 9]


## 6. 행렬의 정렬 - sort()와 argsort()
### 6.1. 행렬 정렬
행렬을 정렬하는 방법은 두 가지가 있다.
* `np.sort()` : 원 행렬은 그대로 유치한 채 원 행렬의 정렬된 행렬을 반환 (원 행렬은 변하지X)
* `nadarray.sort()` : 원 행렬 자체를 정렬한 형태로 반환하며 반환값은 None

In [25]:
org_arr = np.array([3, 1 ,9, 5])
print('원본 행렬 : ', org_arr)

# np.sort()로 정렬
sort_arr1 = np.sort(org_arr)
print('np.sort() 호출 후 반환된 정렬된 행렬 : ', sort_arr1)
print('np.sort() 호출 후 원본 행렬 : ', org_arr)

# ndarray.sort()로 정렬
sort_arr2 = org_arr.sort()
print('org_arr.sort() 호출 후 반환된 행렬 : ', sort_arr2)
print('org_arr.sort() 호출 후 원본 행렬', org_arr)

원본 행렬 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬된 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
org_arr.sort() 호출 후 반환된 행렬 :  None
org_arr.sort() 호출 후 원본 행렬 [1 3 5 9]


기본적으로 정렬은 오름차순이며, 내림차순으로 하고 싶은 경우 `[::-1]`을 적용한다.

In [26]:
sort_arr1_desc = np.sort(org_arr)[::-1]
print('내림차순으로 정렬 : ', sort_arr1_desc)

내림차순으로 정렬 :  [9 5 3 1]


2차원 이상의 배열일 경우 axis 축 값 설정에 따라 축 방향에 따라 정렬을 수행할 수 있다. 이 때 모든 축에 대해서 정렬을 실행한다.

In [27]:
arr2d = np.array([[8, 12],
                  [7, 1 ]])

sort_arr2d_axis0 = np.sort(arr2d, axis=0)
print('row방향으로 정렬 : \n', sort_arr2d_axis0)

sort_arr2d_axis1 = np.sort(arr2d, axis=1)
print('col방향으로 정렬 : \n', sort_arr2d_axis1)

row방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
col방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


### 6.2. 정렬된 행렬의 인덱스 반환하기
원 행렬이 정렬되었을 때 기존 원 행렬의 요소에 대한 인덱스 번호가 필요할 때 `np.argsort()`를 이용한다.
`np.argsort()`는 정렬된 행렬의 원 행렬 인덱스를 ndarray 타입으로 반환한다.
* `ndarray`는 메타 데이터를 가질 수 없다.
* 그러므로 실제 값과 그 값을 뜻하는 메타 데이터를 각각의 `ndarray`로 가져야 한다.
* 이 때 `np.argsort()`를 이용하면 손쉽게 구할 수 있다.

In [28]:
org_arr = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_arr)
print(type(sort_indices))
print('행렬 정렬 시 원 행렬의 인덱스 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원 행렬의 인덱스 :  [1 0 3 2]


내림차순으로 정렬 시의 원 행렬의 인덱스를 구하고 싶을 때 `np.argsort()[::-1]`로 쓰면 된다.

In [29]:
org_arr = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_arr)[::-1]
print('행렬 내림차순 정렬 시 원 행렬의 인덱스 : ', sort_indices_desc)

행렬 내림차순 정렬 시 원 행렬의 인덱스 :  [2 3 0 1]


## 7. 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
### 7.1. 행렬 내적(행렬 곱)
행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 `np.dot()`를 이용해 계산한다.

In [30]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과 : \n', dot_product)

행렬 내적 결과 : 
 [[ 58  64]
 [139 154]]


### 7.2. 전치 행렬
원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 전치 행렬이라고 한다.

In [31]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치행렬 : \n', transpose_mat)

A의 전치행렬 : 
 [[1 3]
 [2 4]]
